'\" t
.\"     Title: yaz-illclient
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 12/03/2009
.\"    Manual: [FIXME: manual]
.\"    Source: YAZ 3.0.52
.\"  Language: English
.\"
.TH "YAZ\-ILLCLIENT" "1" "12/03/2009" "YAZ 3.0.52" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
yaz-illclient \- ILL client
.SH "SYNOPSIS"
.HP \w'\fByaz\-illclient\fR\ 'u
\fByaz\-illclient\fR [\fB\-f\ \fR\fB\fIfilename\fR\fR] [\fB\-v\ \fR\fB\fIloglevel\fR\fR] [\fB\-D\fR\ \fIname=value\fR...] [\fB\-o\fR] [\fB\-u\ \fR\fB\fIuser\fR\fR] [\fB\-p\ \fR\fB\fIpassword\fR\fR] [\fB\-V\fR] [server\-addr]
.SH "DESCRIPTION"
.PP

\fByaz\-illclient\fR
is an client which sends an ISO ILL request to a remote server and decodes the response from it\&. Exactly one server address (
\fIserver\-addr\fR
) must be specified\&.
.SH "OPTIONS"
.PP
\-f \fIfilename\fR]
.RS 4
Specify filename\&.
.RE
.PP
\-v \fIloglevel\fR]
.RS 4
Specify the log level
.RE
.PP
\-D \fIname=value\fR]
.RS 4
Defines name & value pair\&.
.RE
.PP
\-o
.RS 4
Enable OCLC authentication\&.
.RE
.PP
\-u \fIuser\fR]
.RS 4
Specify user\&.
.RE
.PP
\-p \fIpassword\fR]
.RS 4
Specify password\&.
.RE
.PP
\-V
.RS 4
Show yaz\-illclient version\&.
.RE
.SH "EXAMPLES"
.PP
None yet\&.
.SH "FILES"
.PP
None yet\&.
.SH "SEE ALSO"
.PP
yaz(7)
